[package]
name = "rdns"
version = "0.1.0"
authors = ["Trangar <victor.koenders@gmail.com>"]
edition = "2018"

[dependencies]
bitfield = "0.13"
arrayref = "0.3"

[dependencies.byteorder]
version = "1.3"
default-features = false

[profile.release]
lto = true
